language: shell

dist: xenial
addons:
  apt:
    packages:
    - realpath

stages:
  - "Libraries"
  - "Binutils"
  - "GCC - nostdc"
  - "GCC - newlib"
  - "GCC - Linux (musl)"
  - "GDB"
  - "Toolchain - linux musl"
  - "Other tools"

jobs:
  fast_finish: true
  include:
   # Libraries
   - stage: "Libraries"
     env:
     - PACKAGE=lib/isl
   - stage: "Libraries"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/isl

   # or1k toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k

   # rv32 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32

   # rv64 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv64
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv64
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv64
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64

   # lm32 toolchain - no linux
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32

   # ppc64le toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
#   - stage: "GCC - nostdc"
#     env:
#     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=ppc64le
#   - stage: "GCC - newlib"
#     env:
#     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=ppc64le
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=ppc64le
#   - stage: "GDB"
#     env:
#     - PACKAGE=gdb          TOOLCHAIN_ARCH=ppc64le
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le

   # sh2 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=sh
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=sh
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=sh
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=sh
   # OSX
   - stage: "Binutils"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh

   # Full Linux musl toolchain using musl-cross-make
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv64
#   - stage: "Toolchain - Linux MUSL"
#     env:
#     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=ppc64le
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=sh

   # Other tools
   - stage: "Other Tools"
     os: linux
     dist: xenial
     env:
     - PACKAGE=sdcc
   - stage: "Other Tools"
     os: osx
     osx_image: xcode8.3
     addons:
       homebrew:
         packages:
           - x86_64-elf-gcc
     env:
     - PACKAGE=sdcc
   - stage: "Other Tools"
     os: windows
     env:
     - PACKAGE=sdcc

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
