language: shell

dist: xenial
addons:
  apt:
    packages:
    - realpath

stages:
  - name: "No dependencies" # Doesn't depend on anything apart from upstream packages
    if: type != cron
  - name: "Has first level dependencies" # Depends on a package in the "no dependencies" group
    if: type != cron
  - name: "Has second level dependencies" # Depends on a package in the "Has first level dependencies" group
    if: type != cron
  - name: "Main label upload" # Puts Anaconda packages to the main label
    if: type = push AND branch = master
  - name: "Cleanup" # Job for removing old Anaconda labels
    if: type = cron

jobs:
  fast_finish: true
  include:
   - stage: "No dependencies"
     env:
     - PACKAGE=lib/isl
   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/isl

   # or1k toolchain
   - stage: "No dependencies"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k
   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k

   # rv32 toolchain
   - stage: "No dependencies"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32
   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32

   # rv64 toolchain
   - stage: "No dependencies"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv64
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv64
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv64
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv64
   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv64

   # lm32 toolchain - no linux
   - stage: "No dependencies"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32
   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32

   # ppc64le toolchain
   - stage: "No dependencies"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le
#   - stage: "Has first level dependencies"
#     env:
#     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=ppc64le
#   - stage: "Has second level dependencies"
#     env:
#     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=ppc64le
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=ppc64le
#   - stage: "Has second level dependencies"
#     env:
#     - PACKAGE=gdb          TOOLCHAIN_ARCH=ppc64le
   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64le

   # sh2 toolchain
   - stage: "No dependencies"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=sh
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=sh
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=sh
   - stage: "Has second level dependencies"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=sh
   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh

   # Full Linux musl toolchain using musl-cross-make
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv64
#   - stage: "Has first level dependencies"
#     env:
#     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=ppc64le
   - stage: "Has first level dependencies"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=sh

   # Other tools
   - stage: "No dependencies"
     os: linux
     dist: xenial
     env:
     - PACKAGE=sdcc
   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     addons:
       homebrew:
         packages:
           - x86_64-elf-gcc
     env:
     - PACKAGE=sdcc
   - stage: "No dependencies"
     os: windows
     env:
     - PACKAGE=sdcc
  allow_failures:
   - stage: "No dependencies"
     os: windows
     env:
     - PACKAGE=sdcc

  # Move packages from the current label to main
   - stage: "Main label upload"
     os: linux
     dist: xenial
     script:
       - bash $TRAVIS_BUILD_DIR/.travis/master-package.sh

  # Remove old labels
   - stage: "Cleanup"
     os: linux
     dist: xenial
     script:
       - bash $TRAVIS_BUILD_DIR/.travis/cleanup-anaconda.sh

before_install:
 - cp $TRAVIS_BUILD_DIR/.travis/.travis-output.py $TRAVIS_BUILD_DIR/
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - bash $TRAVIS_BUILD_DIR/.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
