package:
  name: toolchain-{{ environ.get('TOOLCHAIN_ARCH') }}-linux-musl
  version: 0.0  # conda-build-prepare will set version based on the git source

source:
  git_url: https://git.zv.io/toolchains/musl-cross-make.git
  git_rev: master
  patches:
    - 0001-quieter-tar.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS
    - TOOLCHAIN_ARCH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl
    - make
  host:
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.15.0
    - cloog
  run:
    - mpc

about:
  home: https://gcc.gnu.org/
  license: GPL
  summary: 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...).'

extra:
  gcc_version: {{ gcc_version }}
  binutils_version: {{ binutils_version }}
  musl_version: {{ musl_version }}
  linux_version: {{ linux_version }}
