name: build-packages
on: [push, pull_request]
jobs:
  packages:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {package: "lib/isl", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "lib/isl", os: "macos-latest", os-name: "osx"}
          - {package: "binutils", toolchain-arch: "or1k", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/nostdc", toolchain-arch: "or1k", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/newlib", toolchain-arch: "or1k", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/linux-musl", toolchain-arch: "or1k", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gdb", toolchain-arch: "or1k", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "binutils", toolchain-arch: "riscv32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/nostdc", toolchain-arch: "riscv32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/newlib", toolchain-arch: "riscv32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/linux-musl", toolchain-arch: "riscv32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gdb", toolchain-arch: "riscv32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "binutils", toolchain-arch: "riscv32", os: "macos-latest", os-name: "osx"}
          - {package: "binutils", toolchain-arch: "riscv64", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/nostdc", toolchain-arch: "riscv64", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/newlib", toolchain-arch: "riscv64", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/linux-musl", toolchain-arch: "riscv64", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gdb", toolchain-arch: "riscv64", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "binutils", toolchain-arch: "riscv64", os: "macos-latest", os-name: "osx"}
          - {package: "binutils", toolchain-arch: "lm32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/nostdc", toolchain-arch: "lm32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/newlib", toolchain-arch: "lm32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gdb", toolchain-arch: "lm32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "binutils", toolchain-arch: "lm32", os: "macos-latest", os-name: "osx"}
          - {package: "binutils", toolchain-arch: "ppc64le", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/linux-musl", toolchain-arch: "ppc64le", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "binutils", toolchain-arch: "ppc64le", os: "macos-latest", os-name: "osx"}
          - {package: "binutils", toolchain-arch: "sh", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/nostdc", toolchain-arch: "sh", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/newlib", toolchain-arch: "sh", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gcc/linux-musl", toolchain-arch: "sh", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "gdb", toolchain-arch: "sh", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "binutils", toolchain-arch: "ppc64le", os: "macos-latest", os-name: "osx"}
          - {package: "toolchain/linux-musl", toolchain-arch: "or1k", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "toolchain/linux-musl", toolchain-arch: "riscv32", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "toolchain/linux-musl", toolchain-arch: "riscv64", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "toolchain/linux-musl", toolchain-arch: "sh", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "sdcc", os: "ubuntu-16.04", os-name: "linux"}
          - {package: "sdcc", os: "macos-latest", os-name: "osx"}
          - {package: "sdcc", os: "windows-latest", os-name: "windows", skip: "true"}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: 'windows: add msys2 to PATH'
      if: matrix.os-name == 'windows'
      run: echo "C:\msys64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell
    - name: 'macos: install dependencies'
      if: matrix.os-name == 'osx'
      run: brew install coreutils boost
    - name: build
      if: matrix.skip != 'true'
      env:
        PACKAGE: ${{ matrix.package }}
        OS_NAME: ${{ matrix.os-name }}
        TOOLCHAIN_ARCH: ${{ matrix.toolchain-arch }}
      run: |
        export PATH="$PATH:/c/ProgramData/Chocolatey/bin/"
        export PATH="$PATH:/c/Program Files/Git/usr/bin/"
        source .github/scripts/common.sh
        bash .github/scripts/fixup-git.sh
        bash .github/scripts/download_sdk.sh
        source .github/scripts/common.sh
        bash .github/scripts/install.sh
        bash .github/scripts/script.sh
    - name: on_success
      env:
        PACKAGE: ${{ matrix.package }}
      if: success() && matrix.skip != 'true'
      run: |
        source .github/scripts/after_success.sh
    - name: on_failure
      env:
        PACKAGE: ${{ matrix.package }}
      if: failure() && matrix.skip != 'true'
      run: |
        source .github/scripts/after_failure.sh
