name: build-packages
on: push
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 39
defaults:
  run:
    shell: bash
jobs:
  libisl-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "lib/isl"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-or1k-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-nostdc-or1k-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-or1k-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-newlib-or1k-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-or1k-linux", "gcc-nostdc-or1k-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-musl-or1k-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gdb-or1k-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-or1k-linux", "gcc-nostdc-or1k-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-riscv32-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-nostdc-riscv32-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-riscv32-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-newlib-riscv32-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-riscv32-linux", "gcc-nostdc-riscv32-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-musl-riscv32-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gdb-riscv32-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-riscv32-linux", "gcc-nostdc-riscv32-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-riscv64-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-nostdc-riscv64-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-riscv64-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-newlib-riscv64-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-riscv64-linux", "gcc-nostdc-riscv64-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-musl-riscv64-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gdb-riscv64-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-riscv64-linux", "gcc-nostdc-riscv64-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-lm32-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-nostdc-lm32-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-lm32-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-newlib-lm32-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-lm32-linux", "gcc-nostdc-lm32-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gdb-lm32-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-lm32-linux", "gcc-nostdc-lm32-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-ppc64le-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "ppc64le"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-musl-ppc64le-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "ppc64le"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-sh-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-nostdc-sh-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-sh-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-newlib-sh-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-sh-linux", "gcc-nostdc-sh-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gcc-musl-sh-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  gdb-sh-linux:
    runs-on: "ubuntu-16.04"
    needs: ["libisl-linux", "binutils-sh-linux", "gcc-nostdc-sh-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  toolchain-or1k-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "toolchain/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  toolchain-riscv32-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "toolchain/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  toolchain-riscv64-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "toolchain/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  toolchain-sh-linux:
    runs-on: "ubuntu-16.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "toolchain/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  libisl-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "lib/isl"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils boost
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-riscv32-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "binutils"
      OS_NAME: "osx"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils boost
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-riscv64-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "binutils"
      OS_NAME: "osx"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils boost
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-lm32-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "binutils"
      OS_NAME: "osx"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils boost
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  binutils-ppc64le-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "binutils"
      OS_NAME: "osx"
      TOOLCHAIN_ARCH: "ppc64le"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils boost
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  sdcc-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sdcc"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  sdcc-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "sdcc"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils boost
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  sdcc-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "sdcc"
      OS_NAME: "windows"
      SKIP: "true"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@move-to-ghactions
  master-package:
    runs-on: "ubuntu-16.04"
    env:
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: urllib3
      - run: |
          bash .github/scripts/install.sh
          python .github/scripts/wait-for-statuses.py
